services:
  sleek-airflow:
    build:
      context: . 
      dockerfile: Dockerfile 
    image: sleek-airflow:latest

    volumes:
      - .:/opt/airflow  # Montar toda la carpeta del proyecto

    ports:
      - "8080:8080"

    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/tasks  
      - PYTHONPATH=/opt/airflow

    command: airflow standalone